### ISSUE TITLE
Overly complicated tooling

### ISSUE THREAD

**Issue by stevenvachon** [Xotic750/to-string-tag-x#3]
* package-lock.json is troublesome for libraries because they're ignored on a consumer's machine, causing them to use different dependency versions than the author/collaborators
* supporting end-of-life Node.js/io.js versions is pointless and only slows CI
* your `pre-push` hook had to be overridden because I am not authorized to use `nsp`

**Comment by stevenvachon** [comment]
I like the concept, as it abstracts `Object.prototype.toString.call` which is confusing to those less experienced with the language.

**Comment by Xotic750** [comment]
I like the concept too, and all the other related projects, but maintenance of all these related projects in this manner is a bit of a nightmare. And then of course, ES6 @@toStringTag came along to spoil the fun of this util too. :)

**Comment by Xotic750** [comment]
Fully updated project to my current tooling. Now, no dependencies. Yes, it's complicated tooling for such small amount of code, but it's my current template. This should addresses most, if not all of your the issues.

**Comment by stevenvachon** [comment]
Heh, yeah, overkill for something this small. You could've used parcel instead of webpack, for example.
