### ISSUE TITLE
Remove useless libraries

### ISSUE THREAD

**Issue by jpike88** [Xotic750/to-string-tag-x#4]
> https://github.com/lodash/lodash/blob/master/isNull.js
> https://github.com/validate-io/undefined/blob/master/lib/index.js

^ Seriously? A dependency for a single line of code?

This is also in:

is-nil-x
to-string-tag-x

I can't believe these are actually libraries. Can you please ditch them.

**Comment by Xotic750** [comment]
The project was built like this on purpose: reuse of code, tests and for cross-browser compatibility. Most of the project is unnecessary these days, as nobody is supporting IE7-8 and the other old browsers that this was designed for. Also the result returned by `toString.call` can be changed by the developer these days ( ECMA2015 @@toStringTag) https://jsfiddle.net/7sLc08gq/ , which makes it no longer a reliable source of information.
